test2
Signed-off-by: Dmitry Chigarev <dmitry.chigarev@intel.com>

diff --git a/.github/workflows/fuzzydata-test.yml b/.github/workflows/fuzzydata-test.yml
--- a/.github/workflows/fuzzydata-test.yml
+++ b/.github/workflows/fuzzydata-test.yml
@@ -21,50 +21,50 @@ concurrency:
   group: ${{ github.workflow }}-${{ github.ref }}
   cancel-in-progress: true
 jobs:
-  test-fuzzydata:
-    runs-on: ubuntu-latest
-    defaults:
-      run:
-        shell: bash -l {0}
-    strategy:
-      matrix:
-        python-version: ["3.8"]
-        engine: ["ray", "dask"]
-    steps:
-      - uses: actions/checkout@v3
-        with:
-          fetch-depth: 1
-      - name: Cache conda
-        uses: actions/cache@v3
-        with:
-          path: |
-            ~/conda_pkgs_dir
-            ~/.cache/pip
-          key:
-            ${{ runner.os }}-conda-${{ hashFiles('environment-dev.yml') }}
-      - uses: conda-incubator/setup-miniconda@v2
-        with:
-          miniforge-variant: Mambaforge
-          miniforge-version: latest
-          use-mamba: true
-          activate-environment: modin
-          environment-file: environment-dev.yml
-          python-version: 3.8
-          channel-priority: strict
-          # we set use-only-tar-bz2 to false in order for conda to properly find new packages to be installed
-          # for more info see https://github.com/conda-incubator/setup-miniconda/issues/264
-          use-only-tar-bz2: false
-      - name: Conda environment
-        run: |
-          conda info
-          conda list
-      - name: test-fuzzydata (engine ${{matrix.engine}}, python ${{matrix.python-version}})
-        run: python -m pytest modin/experimental/fuzzydata/test/test_fuzzydata.py -Wignore::UserWarning --log-file=/tmp/fuzzydata-test-wf-${{matrix.engine}}/run.log --log-file-level=INFO
-        env:
-          MODIN_ENGINE: ${{matrix.engine}}
-      - uses: actions/upload-artifact@v3
-        if: success() || failure()
-        with:
-           name: fuzzydata-test-workflow-${{matrix.engine}}
-           path: /tmp/fuzzydata-test-wf-${{matrix.engine}}/* # Must match output dir in test_fuzzydata.py
-           if-no-files-found: error
+  # test-fuzzydata:
+  #   runs-on: ubuntu-latest
+  #   defaults:
+  #     run:
+  #       shell: bash -l {0}
+  #   strategy:
+  #     matrix:
+  #       python-version: ["3.8"]
+  #       engine: ["ray", "dask"]
+  #   steps:
+  #     - uses: actions/checkout@v3
+  #       with:
+  #         fetch-depth: 1
+  #     - name: Cache conda
+  #       uses: actions/cache@v3
+  #       with:
+  #         path: |
+  #           ~/conda_pkgs_dir
+  #           ~/.cache/pip
+  #         key:
+  #           ${{ runner.os }}-conda-${{ hashFiles('environment-dev.yml') }}
+  #     - uses: conda-incubator/setup-miniconda@v2
+  #       with:
+  #         miniforge-variant: Mambaforge
+  #         miniforge-version: latest
+  #         use-mamba: true
+  #         activate-environment: modin
+  #         environment-file: environment-dev.yml
+  #         python-version: 3.8
+  #         channel-priority: strict
+  #         # we set use-only-tar-bz2 to false in order for conda to properly find new packages to be installed
+  #         # for more info see https://github.com/conda-incubator/setup-miniconda/issues/264
+  #         use-only-tar-bz2: false
+  #     - name: Conda environment
+  #       run: |
+  #         conda info
+  #         conda list
+  #     - name: test-fuzzydata (engine ${{matrix.engine}}, python ${{matrix.python-version}})
+  #       run: python -m pytest modin/experimental/fuzzydata/test/test_fuzzydata.py -Wignore::UserWarning --log-file=/tmp/fuzzydata-test-wf-${{matrix.engine}}/run.log --log-file-level=INFO
+  #       env:
+  #         MODIN_ENGINE: ${{matrix.engine}}
+  #     - uses: actions/upload-artifact@v3
+  #       if: success() || failure()
+  #       with:
+  #          name: fuzzydata-test-workflow-${{matrix.engine}}
+  #          path: /tmp/fuzzydata-test-wf-${{matrix.engine}}/* # Must match output dir in test_fuzzydata.py
+  #          if-no-files-found: error
